version: "3.2"

services:
  object-detection:
    build:
      dockerfile: research/object_detection/dockerfiles/tf1/Dockerfile
      context: .
      labels:
        - tensorflow/object-detection:latest
    ports:
      - 8888:8888
      - 6006:6006
    volumes:
      - type: bind
        source: /home/samot/hd/samot/Downloads/docker-tf-gpu-jupyter/our_project/models/data/
        target: /usr/local/lib/python3.6/dist-packages/tensorflow/models/data
      - type: bind
        source: /home/samot/hd/samot/Downloads/docker-tf-gpu-jupyter/our_project/models/modelname/
        target: /usr/local/lib/python3.6/dist-packages/tensorflow/models/model
      - type: bind
        source: /home/samot/hd/samot/Downloads/docker-tf-gpu-jupyter/our_project/models/annotations/
        target: /usr/local/lib/python3.6/dist-packages/tensorflow/models/annotations
      - type: bind
        source: /home/samot/hd/samot/Downloads/docker-tf-gpu-jupyter/dataset/ColorImages/
        target: /usr/local/lib/python3.6/dist-packages/tensorflow/models/images
      - type: bind
        source: /home/samot/hd/samot/Downloads/docker-tf-gpu-jupyter/dataset/Annotations/
        target: /usr/local/lib/python3.6/dist-packages/tensorflow/models/annotations/xmls
    command: ["--gpu"]

